/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.component;

import com.main.Main;
import com.ui.PanelDanhSachSanPham;
import com.ui.QuanlytaikhoanJDialog;
import com.ui.panelQuanLyTaiKhoan;
import com.utils.Auth;
import javax.swing.JOptionPane;

/**
 *
 * @author Thai
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBanHang = new javax.swing.JButton();
        btnQLSanPham = new javax.swing.JButton();
        btnQLHoaDon = new javax.swing.JButton();
        btnQLHoaDon1 = new javax.swing.JButton();
        btnQLHoaDon2 = new javax.swing.JButton();
        btnQLHoaDon3 = new javax.swing.JButton();
        btnQLHoaDon4 = new javax.swing.JButton();
        btnQLTaikhoan = new javax.swing.JButton();

        btnBanHang.setText("Bán hàng");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnQLSanPham.setText("Quản lý sản phẩm");
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });

        btnQLHoaDon.setText("Quản lý hóa đơn");
        btnQLHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDonActionPerformed(evt);
            }
        });

        btnQLHoaDon1.setText("Quản lý thuộc tính");
        btnQLHoaDon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDon1ActionPerformed(evt);
            }
        });

        btnQLHoaDon2.setText("Quản lý nhân viên");
        btnQLHoaDon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDon2ActionPerformed(evt);
            }
        });

        btnQLHoaDon3.setText("Quản lý khuyến mãi");
        btnQLHoaDon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDon3ActionPerformed(evt);
            }
        });

        btnQLHoaDon4.setText("Thống kê");
        btnQLHoaDon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHoaDon4ActionPerformed(evt);
            }
        });

        btnQLTaikhoan.setText("Quản lý tài khoản");
        btnQLTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTaikhoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLHoaDon2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLHoaDon3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLHoaDon4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
            .addComponent(btnQLTaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHoaDon3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnQLTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHoaDon2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQLHoaDon4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        Main.changeForm(new PanelDanhSachSanPham());
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void btnQLHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDonActionPerformed

    private void btnQLHoaDon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDon1ActionPerformed

    private void btnQLHoaDon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDon2ActionPerformed

    private void btnQLHoaDon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDon3ActionPerformed

    private void btnQLHoaDon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHoaDon4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQLHoaDon4ActionPerformed

    private void btnQLTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTaikhoanActionPerformed
        Main.changeForm(new panelQuanLyTaiKhoan());
    }//GEN-LAST:event_btnQLTaikhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnQLHoaDon;
    private javax.swing.JButton btnQLHoaDon1;
    private javax.swing.JButton btnQLHoaDon2;
    private javax.swing.JButton btnQLHoaDon3;
    private javax.swing.JButton btnQLHoaDon4;
    private javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton btnQLTaikhoan;
    // End of variables declaration//GEN-END:variables
}
