/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ui;

import com.dao.ChiTietHoaDonDAO;
import com.entity.HoaDon;
import com.main.Main;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Thai
 */
public class PanelChiTietHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form PanelChiTietHoaDon
     */
    public static HoaDon hoaDon = null;
    SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
    DefaultTableModel model;
    ChiTietHoaDonDAO daoCTHD = new ChiTietHoaDonDAO();

    public PanelChiTietHoaDon() {
        initComponents();
        model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setColumnIdentifiers(new String[]{"Mã CTSP", "Tên sản phẩm", "Số lượng", "Giá"});
        TableColumnModel column = tblChiTietHoaDon.getColumnModel();
        int[] size = {100, 400, 80, 120};
        for (int i = 0; i < model.getColumnCount(); i++) {
            column.getColumn(i).setPreferredWidth(size[i]);
        }
        showForm();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChiTietHoaDon = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JLabel();
        txtKhachHang = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JLabel();
        txtTrangThai = new javax.swing.JLabel();
        txtTongTienCuoi = new javax.swing.JLabel();
        txtTongTienGoc = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Chi tiết hóa đơn");
        jLabel18.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mã hóa đơn");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Người bán");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Thời gian bán");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Khách hàng");

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblChiTietHoaDon);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tổng tiền gốc");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tổng tiền cuối");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Khuyến mãi");

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMaHD.setText("null");

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTaiKhoan.setText("null");

        txtKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKhachHang.setText("null");

        txtThoiGian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtThoiGian.setText("null");

        txtKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKhuyenMai.setText("null");

        txtTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTrangThai.setText("null");

        txtTongTienCuoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongTienCuoi.setText("null");

        txtTongTienGoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTongTienGoc.setText("null");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChiTietHoaDonLayout = new javax.swing.GroupLayout(panelChiTietHoaDon);
        panelChiTietHoaDon.setLayout(panelChiTietHoaDonLayout);
        panelChiTietHoaDonLayout.setHorizontalGroup(
            panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                        .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaHD))
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKhachHang)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChiTietHoaDonLayout.createSequentialGroup()
                        .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTrangThai))
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKhuyenMai)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongTienGoc))
                            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongTienCuoi)))
                        .addGap(194, 194, 194))
                    .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTaiKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThoiGian)
                        .addGap(202, 202, 202))))
        );
        panelChiTietHoaDonLayout.setVerticalGroup(
            panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChiTietHoaDonLayout.createSequentialGroup()
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(btnThoat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtTaiKhoan)
                    .addComponent(txtThoiGian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtKhuyenMai)
                    .addComponent(txtTongTienGoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtTrangThai)
                    .addComponent(txtTongTienCuoi))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelChiTietHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelChiTietHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        Main.changeForm(new PanelHoaDon());
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelChiTietHoaDon;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JLabel txtKhachHang;
    private javax.swing.JLabel txtKhuyenMai;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JLabel txtTaiKhoan;
    private javax.swing.JLabel txtThoiGian;
    private javax.swing.JLabel txtTongTienCuoi;
    private javax.swing.JLabel txtTongTienGoc;
    private javax.swing.JLabel txtTrangThai;
    // End of variables declaration//GEN-END:variables

    private void showForm() {
        txtMaHD.setText(hoaDon.getMaHD());
        txtKhachHang.setText(hoaDon.getMaKH());
        txtKhuyenMai.setText(hoaDon.getMaKM());
        txtTaiKhoan.setText(hoaDon.getTaiKhoan());
        txtThoiGian.setText(formater.format(hoaDon.getThoiGianBan()));
        txtTongTienCuoi.setText(hoaDon.getTongTienCuoi() + "");
        txtTongTienGoc.setText(hoaDon.getTongTienGoc() + "");
        txtTrangThai.setText(hoaDon.getTrangThai());
    }

    private void showTable() {
        model.setRowCount(0);
        for(Object[] cthd : daoCTHD.getAllHoaDonChiTiet(hoaDon.getMaHD())){
            model.addRow(cthd);
        }
    }
}
