/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ui;

import com.dao.TaiKhoanDAO;
import com.entity.SanPham;
import com.entity.TaiKhoan;
import com.main.Main;
import com.utils.Auth;
import com.utils.FormatDate;
import com.utils.Rounding;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author DELL
 */
public class PanelQuanLyNhanVien extends javax.swing.JPanel {

    TaiKhoanDAO DAO = new TaiKhoanDAO();
    DefaultTableModel model = new DefaultTableModel();
    int index = -1;

    /**
     * Creates new form PanelQuanLyNhanVien
     */
    public PanelQuanLyNhanVien() {
        initComponents();
        filltable(DAO.getall());
    }

    void filltable(List<TaiKhoan> List) {
        model = (DefaultTableModel) tbl_qlnv.getModel();
        model.setRowCount(0);
        for (TaiKhoan x : List) {
            model.addRow(x.todatarow());
        }
    }

//    void showdata(int index) {
//        TaiKhoan tk = DAO.getall().get(index);
//        txt_taikhoan.setText(tk.getTaikhoan());
//        txt_matkhau.setText(tk.getMatkhau());
//        txt_hovaten.setText(tk.getTen());
//        txt_ngaysinh.setText(FormatDate.toString(tk.getNgaysinh()));
//        txt_sdt.setText(tk.getSdt());
//        txt_email.setText(tk.getEmail());
//        txt_cccd.setText(tk.getCCCD());
//        if (tk.isChucvu()) {
//            radio_quanly.setSelected(true);
//        } else {
//            radio_nhanvien.setSelected(true);
//        }
//    }
//
//    TaiKhoan readfrom() {
//        String tkhoan = txt_taikhoan.getText();
//        String matkhau = txt_matkhau.getText();
//        String cccd = txt_cccd.getText();
//        String ten = txt_hovaten.getText();
//        Date ngaySinh = FormatDate.toDate(txt_ngaysinh.getText());
//        String sdt = txt_sdt.getText();
//        String email = txt_email.getText();
//        boolean chucvu;
//        if (radio_quanly.isSelected()) {
//            chucvu = true;
//        } else {
//            chucvu = false;
//        }
//        return new TaiKhoan(tkhoan, matkhau, ten, ngaySinh, sdt, email, cccd, chucvu);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_qlnv = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();

        tbl_qlnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tài Khoản", "Họ và Tên", "Ngày Sinh", "Số Điện Thoại", "Chức Vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_qlnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_qlnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_qlnv);

        btn_them.setText("Thêm Nhân VIên");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 346, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        Main.changeForm(new Panelthemnhanvien());
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_qlnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_qlnvMouseClicked
        
    }//GEN-LAST:event_tbl_qlnvMouseClicked

    private void txt_timkiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyPressed
        
    }//GEN-LAST:event_txt_timkiemKeyPressed

    private void txt_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyReleased
        showTable();
    }//GEN-LAST:event_txt_timkiemKeyReleased
    private void showTable() {
       
            DefaultTableModel model = (DefaultTableModel) tbl_qlnv.getModel();
            model.setRowCount(0);
            TableColumnModel column = tbl_qlnv.getColumnModel();
            int[] size = {100, 400, 130, 130,130};
            for (int i = 0; i < model.getColumnCount(); i++) {
                column.getColumn(i).setPreferredWidth(size[i]);
            }

            String key = txt_timkiem.getText();
        try {
            for (TaiKhoan sp : DAO.selectAll()) {
                if (sp.getTaikhoan().toUpperCase().contains(key.toUpperCase()) || sp.getTen().toUpperCase().contains(key.toUpperCase())) {
                    model.addRow(new Object[]{sp.getTaikhoan(), sp.getTen(), sp.getNgaysinh(), sp.getSdt(),sp.chucvuhienthi()});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelQuanLyNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_them;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_qlnv;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
